### PR TITLE
Added language extensions support to the hgettext tool + support for C pre-processing

### PR DESCRIPTION
**Pull request by NH002**
Also tested the package with GHC 8.0.1.

Solves #19.

### CODE REVIEW

**Comment by NH002** [comment]
Solves now #21 as well.

**Comment by Bodigrim** [comment]
@phadej @andreasabel does anyone of you have commit bits here?

**Comment by andreasabel** [comment]
I can rule over the `haskell-hvr`repos, but I don't have the hackage rights for this tool: https://hackage.haskell.org/package/hgettext/maintainers/

**Comment by andreasabel** [comment]
Continued in #22. (The present PR isn't set up so that others can complement it; I cannot push to `NH002:master`)

**Pull request closed without merging**
