### PR TITLE
wip: Fix build with cabal-2.4

### LINKED ISSUE #15: Build fails with Cabal 2.4
[`matchFileGlob`](https://www.stackage.org/haddock/lts-10.9/Cabal-2.0.1.1/Distribution-Simple-Utils.html#g:10) was removed in 2.4 (https://github.com/haskell/cabal/pull/5284) and [`Distribution.Simple.Glob.matchDirFileGlob`](https://www.stackage.org/haddock/lts-13.9/Cabal-2.4.1.0/Distribution-Simple-Glob.html#v:matchDirFileGlob) with widely different type is supposed to be used instead.

I am not really sure where are we supposed to get the `PackageDescription` argument value. Perhaps something like https://github.com/google/proto-lens/pull/242/files#diff-4fe9daabe5a3a972435eb21087de0259R183 could work.

### PR DESCRIPTION
**Pull request by jtojnar**
Closes: https://github.com/haskell-hvr/hgettext/issues/15

### CODE REVIEW

**Comment by juhp** [comment]
This fixes the build for me, thanks

**Comment by jtojnar** [comment]
Note that this is not a right way to do this, see https://github.com/haskell/cabal/pull/5284#issuecomment-472877556

**Comment by juhp** [comment]
Thanks, can `cabalVersion` not be used for this?

**Comment by jtojnar** [comment]
If I recall correctly, it needs to be not the version of Cabal but of the spec listed in the cabal file. It should be routed similarly to this: https://github.com/google/proto-lens/pull/242/files#diff-4fe9daabe5a3a972435eb21087de0259R183

**Comment by juhp** [comment]
Okay, I am trying to get my head around this - would the Cabal lib linked by the hgettext lib and Setup not provide the correct cabalVersion anyway?

**Comment by jtojnar** [comment]
If I recall correctly, you declare glob patterns in `x-gettext-po-files` field in the cabalfile for the `Setup.hs` hook to find the files. Glob pattern parsing is version dependent and for other fields like [`data-files`](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-data-files) it is controlled by the spec version set by [`cabal-version`](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-data-files), you would probably want the same for `x-gettext-po-files`. This PR currently fixes the glob style to one used by the 2.0 spec.

You definitely do not want to have it change based on the cabal version the user runs, which is what [`cabalVersion`](https://www.stackage.org/haddock/lts-13.9/Cabal-2.4.1.0/Distribution-Simple-Utils.html#v:cabalVersion) returns, as far as I understand it.

**Comment by juhp** [comment]
> You definitely do not want to have it change based on the cabal version the user runs, which is what cabalVersion returns, as far as I understand it.

Okay thank you for the explanation, that does make sense.

**Pull request closed without merging**
